repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        files: src
        args: ["--fix"]
      - id: ruff-format
        files: src
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        files: src
        args: ["--install-types", "--non-interactive"]
        additional_dependencies:
          - pydantic==2.6.4
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.7.1
    hooks:
      - id: poetry-export
        pass_filenames: false
        args: ["--without-hashes", "--output", "requirements.txt"]
        files: ^(pyproject.toml|poetry.lock)$
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-install
default_language_version:
  python: python3.11
