version: "3.8"
services:
  caddy:
    build:
      context: ../static
    container_name: caddy
    command:
      ["caddy", "file-server", "--listen=:${CADDY_PORT}", "--root=/static"]
    ports:
      - "${LOCAL_CADDY_PORT}:${CADDY_PORT}"

  backend:
    build:
      context: ../
    container_name: backend
    command:
      [
        "granian",
        "--interface=asgi",
        "--host=${SERVER_HOST}",
        "--port=${SERVER_PORT}",
        "src.main:app",
      ]
    ports:
      - "${LOCAL_SERVER_PORT}:${SERVER_PORT}"
